### PR TITLE
[feature] Fix png crc signature of each chunk while writing 

### LINKED ISSUE #5: [bug] Some pngs silently fail to be stripped after printing `crc failure`
See image + test on branch here: https://github.com/superseriousbusiness/exif-terminator/tree/fish_png_error

Discovered by https://github.com/superseriousbusiness/gotosocial/issues/2340

### PR DESCRIPTION
**Pull request by tsmethurst**
Does what it says on the tin :) closes #5

### CODE REVIEW

File: terminator.go [hunk 1]
```diff
@@ -93,42 +101,50 @@ func terminateWebp(scanner *bufio.Scanner, writer io.WriteCloser) error {
...
+	go scanAndClose(scanner, writer)
 	return nil
 }
 
 func terminatePng(scanner *bufio.Scanner, writer io.WriteCloser) error {
 	ps := pngstructure.NewPngSplitter()
 
+	// Don't bother checking CRC;
+	// we're overwriting it anyway.
+	ps.DoCheckCrc(false)
```
Comment (tsmethurst) [inline terminator.go:117]: This is actually necessary because if we don't set it to false, we can't fix broken chunks because they fail to read very quietly.

Comment (daenney) [reply terminator.go:117]: The issue with doing this is then we also don't check the CRC on the required sections, like `IHDR` and `IDAT`. If CRC checks on those fail the image is probably just broken or shenanigans are afoot.

The library doesn't seem to have an option to only disable it for ancillary chunks, so I suppose this is the best we can do for now.

Comment (daenney) [reply terminator.go:117]: Ah although, since we're now swapping out this library for our fork of it, we could fix that there.

Comment (tsmethurst) [reply terminator.go:117]: Ah true true. We do try to parse the png at the end of the process though using `image/png`. So I think that can still fail if there's funny business going on.

Comment (daenney) [reply terminator.go:117]: Right we do. That's probably good enough of a backstop.
